### ISSUE TITLE
Epiviz not working

### ISSUE THREAD

**Issue by beamilon** [IGS/gEAR#359] opened 2022-07-13 18:17 UTC
@jorvis @songeric1107 @adkinsrs None of the epigenetics data are loading.

**Comment by adkinsrs** [comment] 2022-07-13 18:20
Looks like the GET call to https://umgear.org/epivizfile (+ params) is borked.  Does @jkanche have a potential solution.

Example URL -> https://umgear.org/index.html?multigene_plots=0&layout_id=1c98096b&gene_symbol_exact_match=1&gene_symbol=Sox2

**Comment by songeric1107** [comment] 2022-07-13 18:28
create a duplicate ticket under Joshua's account and assign it to Jayaram.

**Comment by jorvis** [comment] 2022-07-13 18:38
It's fine to leave the ticket here - I'll send it to Jayaram.  I've double checked that the needed drive for Epiviz was remounted after the reboot.

**Comment by jkanche** [comment] 2022-07-13 21:55
was the instance restarted or redeployed ?

**Comment by jorvis** [comment] 2022-07-14 03:39
Restarted, yes.

**Comment by beamilon** [comment] 2022-07-15 14:38
@jkanche Ronna would like to know if it is going to be fixed by Monday for the workshop?

**Comment by jorvis** [comment] 2022-07-15 16:06
Error messages show Epiviz can't communicate with a process on port 8000, and I can confirm nothing is listening on that port:

$ sudo lsof -i -P -n | grep LISTEN. | grep 8000

Still looking.

**Comment by jkanche** [comment] 2022-07-15 17:04
I can't find `virtualenv` preinstalled in any of these. How were you creating virtual environment s?

**Comment by jorvis** [comment] 2022-07-15 17:08
We don't use virtualenv, just paths.  There is /usr/bin/python3 and more custom ones under /opt

**Comment by jorvis** [comment] 2022-07-15 17:10
/usr/bin actually had python2 and python3, but no 'python'.  I've symlinked 'python' as python2 following the usual system convention.

**Comment by adkinsrs** [comment] 2022-07-15 17:14
@jkanche The virtualenv instance of Python (for Flask usage) was removed back in mid- to late-2020 in an effort to have codebase use just one instance of Python instead of two.

**Comment by jkanche** [comment] 2022-07-15 21:08
ok its back - https://umgear.org/index.html?multigene_plots=0&layout_id=1c98096b&gene_symbol_exact_match=1&gene_symbol=Sox2

**Comment by jorvis** [comment] 2022-07-15 21:16
Tested and resolved.  Will work for a  better integrated python solution after the upcoming workshop.

**Closed by jorvis** 2022-07-15 21:16 UTC
