### ISSUE TITLE
Displaying bugs(reported by Ronna)

### ISSUE THREAD

**Issue by songeric1107** [IGS/gEAR#149] opened 2022-01-07 02:11 UTC
1. can not close the floating window after viewing "info"
![Screen Shot 2022-01-06 at 9 08 34 PM](https://user-images.githubusercontent.com/6730079/148479897-ffa769db-eeb5-4981-95f8-3368e23f25db.png)
2. Profile showed duplicate gene symbols on the left panel and duplicate display panels

**Comment by adkinsrs** [comment] 2022-01-07 02:15
This is a well-known, long-standing issue for @jorvis and I. The crux of this is a combination of race conditions firing, and multiple entrypoints into the functions that set the layout profile and load the display panels. I have been working this afternoon in an attempt to reorganize some of the code that generates the panels, and I hope I can have something working by tomorrow.

This may also be a duplicate of another ticket somewhere.... if so I will close this version and reference that one.

**Comment by adkinsrs** [comment] 2022-01-07 21:41
I believe I have resolved this.

@songeric1107 and @JPReceveur , please search for a few genes (single-gene and multi-gene view) from the main page on the gear-devel server.  In addition, look into a) toggling the "multigene toggle" on the gene display panel page and click Search, b) switch profiles, and c) do a refresh of the gene display panel page (either Ctrl-R or the Refresh button on the browser).  Do these various things a few times, as the bug randomly generates as a result of a race condition (where the panel loading may happen faster than the user login check process).  Generally with the bug will see panels be duplicated or genes (in the single-gene search mode) duplicate on the left side of the page.

**Comment by JPReceveur** [comment] 2022-01-10 13:12
@adkinsrs Tested as described above in both single and multigene view and bug did not appear. Did not have any issue closing info or display pop-up windows.

**Comment by songeric1107** [comment] 2022-01-10 15:20
@adkinsrs I tested on devel , I could not duplicate the problems as reported by Ronna

**Comment by adkinsrs** [comment] 2022-01-10 15:21
Excellent!  I am closing this ticket for now.  If anyone see these issues, feel free to re-open the ticket.

**Closed by adkinsrs** 2022-01-10 15:21 UTC
Labels: bug
