### ISSUE TITLE
gEAR staging: Exact match gene search behavior

### ISSUE THREAD

**Issue by JPReceveur** [IGS/gEAR#795] opened 2024-07-19 18:11 UTC
In gene expression search if you search for a multi gene display and then switch back the toggle to single gene display, when you hit search for the second time you receive the message 'must select two genes' even though you are searching with the single gene display highlighted.

Also if you untoggle exact match and choose multigene display (e.g. search for 'sox' in the hearing collection) it returns the message 'The given gene symbol(s) nor corresponding orthologs were not found in this dataset.' while in the single gene display it returns 54 results. I would expect the multigene display with exact match not selected to make a heatmap with all the genes that show up in the single gene display list.

**Comment by adkinsrs** [comment] 2024-07-19 18:21
The first paragraph is being addressed in #719 in https://github.com/IGS/gEAR/issues/719#issuecomment-2239237528

**Comment by adkinsrs** [comment] 2024-07-22 19:43
With the fixes I made 3 days ago, now if you search multi-gene displays and one gene with "exact match" turned off, the "need two genes" validation warning happens. Need to a) bypass that error, and b) fix the 2nd paragraph in the opening comment

**Comment by adkinsrs** [comment] 2024-07-22 20:02
Also worth noting that the exact match check is mainly used to in gene annotation and results list work.  Have a fuzzy match has never been an implemented option with the multigene curator.

This issue is also a duplicate of #640 and once was addressed in #499

**Comment by adkinsrs** [comment] 2024-08-08 19:35
Complete

**Closed by adkinsrs** 2024-08-08 19:35 UTC
Labels: bug
