### ISSUE TITLE
scan "info" field for a dataset for URLs and hyperlink them

### ISSUE THREAD

**Issue by carlocolantuoni** [IGS/gEAR#591] opened 2023-09-06 12:49 UTC
currently i put links to other related NeMO profiles in the "info" section of a dataset as simple text - can we scan the text in the "info" section and make them hyperlinks?

this would really enhance the navigational abilities across profiles and datasets - as does #584

**Comment by jorvis** [comment] 2023-09-20 17:01
Closing as duplicate of #583

**Closed by jorvis** 2023-09-20 17:01 UTC
Labels: PostProjectionTASKS
